on: push
name: 🚀 Deploy to Stage
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - name: Build Project
      run: |
        yarn install
        yarn build
        
    - name: List output files
      run: find build/ -print
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.STAGE_FTP_HOST }}
        username: ${{ secrets.STAGE_FTP_USERNAME }}
        password: ${{ secrets.STAGE_FTP_PASSWORD }}
        local-dir: build/
        server-dir: /
