on:
  push:
      branches:
        - stage

name: 🚀 Deploy to Stage

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build Project
      env:
        CI: false
        REACT_APP_MAIN_SYSTEM_URL: "https://kronos.stage.br.ivao.aero"
        REACT_APP_API_HOST: ${{ secrets.STAGE_API_HOST }}
        REACT_APP_LOGO_URL: "https://assets.br.ivao.aero/logos/tag_white.png"
      run: yarn build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.STAGE_FTP_HOST }}
        username: ${{ secrets.STAGE_FTP_USERNAME }}
        password: ${{ secrets.STAGE_FTP_PASSWORD }}
        local-dir: build/
        server-dir: /
